### ISSUE TITLE
[Feature] Remember timestamp viewing preferences (relative time booleans)

### ISSUE THREAD

**Issue by techygrrrl** [folklorelabs/pockest-helper#107]
It would be useful if the extension remembered my timestamp viewing preference.

**Reason**: From the perspective of "am I on track?" it's not helpful to see relative time since I would have to do math from the hatch date to current time to see if it's on track and I have to toggle it each time. I prefer to view the timestamps rather than relative time. 

<img width="671" alt="image" src="https://github.com/user-attachments/assets/e9da9a88-855b-4dc5-8010-941bb52f2ec4">

### Possible implementation

If you don't have the time to do this and you like the idea of it, I could help with this, but I wanted to know implementation-wise what you'd prefer. Perhaps a new localStorage key `PockestHelperConfig` that can be used for viewing preferences or other preferences unrelated to the plan. 

To start it could be something like this:

```json
{
  "useRelativeTimeForCareLog": false,
  "useRelativeTimeForPresetPlan": true,
  "useRelativeTimeForCompletionStats": true
}
```

We can load it from state in `getStateFromLocalStorage()` with the other states:

```diff
const INITIAL_STATE = {
   /* ... */
   error: null,
   initialized: false,
   invalidSession: false,
+  userConfig: {
+    useRelativeTimeForCareLog: false,
+    useRelativeTimeForPresetPlan: true,
+    useRelativeTimeForCompletionStats: true,
+  }
 };
```

### relative time

<img width="663" alt="image" src="https://github.com/user-attachments/assets/1459a934-e2ad-468f-909c-6b278c1462d4">

### timestamps

<img width="666" alt="image" src="https://github.com/user-attachments/assets/35e97a5f-7a7a-40f9-a0e3-21992206c194">

**Comment by techygrrrl** [comment]
An alternative approach that I thought of is maybe we can highlight the next step in the plan so we can easily see if we're on track, since that's the ultimate goal. And if that's the case, maybe a different UI is appropriate. Or some other more visual way to see if we're on track. Right now we have to look at the Preset Plan and the Care Log and match them. It might be easier to see if there was an alternative UI for this to more easily see if we're on track.

**Comment by folklorelabs** [comment]
As for the remembering of the relative time option preference. This is easy enough to add in :D

I'll probably just add a new log settings object to localStorage for these (and any other future settings we might have for this page later)

**Comment by techygrrrl** [comment]
That sounds great regarding the improved logs. 

It sounds like a lot of crucial functionality relies on the egg timestamps being in sync. Does the pockest servers provide any historical data from last trainings/feedings/cleanings/matches/etc. that can be used help get it back on track? Or is using the timestamps the only way?

Being able to reverse engineer failures and figure out what went wrong, and hand-holding the user as much as possible would be awesome.

As an aside, I don't know how anyone could successfully hatch stickers and mementos without the help of the pockest book and this extension lol. I tried to follow the failed Zangief plan, but I wasn't sure what to do about matches, and I tried to feed and clean on schedule, but I must've went wrong somewhere because it went down the wrong path.

**Comment by folklorelabs** [comment]
They do not. The only history we have is baked into their ["encyclopedia" endpoint](https://www.streetfighter.com/6/buckler/api/minigame/encyclopedia/list), but this only includes mementos/monsters owned by the logged in user. Everything else is included in a data snapshot that is sent along with [the status endpoint](https://www.streetfighter.com/6/buckler/api/minigame/status) as well as any of the action calls (cleaning, training, etc).

That being said, you gave me an idea in your other thread with how we could somewhat accurately display "completion" within the preset plan. I think I can display the clean/feed complete/incomplete indicators within the plan log because these have clearly defined 1 hour windows. And if we miss one of these with the actual addon I don't think it's bad to show it as a failure in the preset plan.

Training may be a little more difficult because the window is more fluid so I'll have to think about how we can accurately catch a success, but I think this is also do-able.

**Comment by folklorelabs** [comment]
Basically it'd look like this:
```
[Pockest Helper v1.2.0-rc.52] Target 1BRS5 (Age 5)
☑ [8/10/2024, 12:31:24 AM] Feed (♥♥♥♥♥♥)
☑ [8/10/2024, 12:31:24 AM] Train S
☑ [8/10/2024, 4:31:24 AM] Feed (♥♥♥♥♥♥)
☑ [8/10/2024, 8:31:24 AM] Feed (♥♥♥♥♥♥)
☐ [8/10/2024, 12:31:24 PM] Clean
☐ [8/10/2024, 12:31:24 PM] Feed (♥♥♥♥♥♥)
☐ [8/10/2024, 12:31:24 PM] Train S
☐ [8/11/2024, 12:31:24 AM] Train S
☐ [8/11/2024, 12:31:24 PM] Clean
☐ [8/11/2024, 12:31:24 PM] Feed (♥♥♥♥♥♥)
☐ [8/11/2024, 12:31:24 PM] Train S
☐ [8/11/2024, 4:31:24 PM] Feed (♥♥♥♥♥♥)
☐ [8/11/2024, 6:31:24 PM] Clean
☐ [8/11/2024, 8:31:24 PM] Feed (♥♥♥♥♥♥)
☐ [8/12/2024, 12:31:24 AM] Train S
☐ [8/12/2024, 8:31:24 PM] Stop curing
```

**Comment by techygrrrl** [comment]
That looks great! Augmenting the existing plan with the completed state would help us see if we're on track without having to refer to the logs. Then if we don't see one checked off, we could scroll back up and see what could've gone wrong.

**Comment by folklorelabs** [comment]
[v1.2.0](https://github.com/folklorelabs/pockest-helper/releases/tag/v1.2.0) has been released and with it comes the plan log mentioned above as well as all log default options being set to absolute by default.

Thanks again for all your help here :D

**Comment by techygrrrl** [comment]
> [v1.2.0](https://github.com/folklorelabs/pockest-helper/releases/tag/v1.2.0) has been released and with it comes the plan log mentioned above as well as all log default options being set to absolute by default.

Nice! With those checkboxes too? The ones mentioned above like this:

```
☑ [8/10/2024, 8:31:24 AM] Feed (♥♥♥♥♥♥)
☐ [8/10/2024, 12:31:24 PM] Clean
```

That would be dope!
