### ISSUE TITLE
Restore seconds to timestamp

### ISSUE THREAD

**Issue by techygrrrl** [folklorelabs/pockest-helper#114]
Version: 1.2.1-rc.3

I noticed the seconds were removed from timestamps in 00552a79d473511c98b96cb09071e8c89ff189e9

Can this be restored, either globally or for advanced mode? It's helpful for debugging.

**Comment by folklorelabs** [comment]
I can add them back in. I didn't think anyone cared about having that much precision when it comes to monitoring the monster and considering the log panel is already tight for space I figured I'd save everyone a few characters haha

**Comment by folklorelabs** [comment]
Added back in rc.4
https://github.com/folklorelabs/pockest-helper/releases/tag/v1.2.1-rc.4

**Comment by techygrrrl** [comment]
Awesome thanks! Yeah, I like all of the dataz lol
