### ISSUE TITLE
[Feature] Purple egg support 🟣🥚

### ISSUE THREAD

**Issue by techygrrrl** [folklorelabs/pockest-helper#118]
I just noticed a new egg today! Not sure if it's on your radar.

![image](https://github.com/user-attachments/assets/db84c180-244a-4ebe-bbba-4b2ad276c695)

**Comment by folklorelabs** [comment]
Yep! We're hard at work figuring out the routes. You should [join us on Discord](https://discord.gg/3m6x9mGCRe) if you're curious to see the Discord reports or discussion surrounding new eggs :D

**Comment by techygrrrl** [comment]
> Yep! We're hard at work figuring out the routes. You should [join us on Discord](https://discord.gg/3m6x9mGCRe) if you're curious to see the Discord reports or discussion surrounding new eggs :D

Nice! Just joined, thanks! 🟣 🥚
