### ISSUE TITLE
Output the current version number somewhere

### ISSUE THREAD

**Issue by techygrrrl** [folklorelabs/pockest-helper#119]
It would be great to see the current version number so when a new version is published, we can see how far behind we are and what we're missing out on.

**Comment by folklorelabs** [comment]
Great idea. I'll update the alert that pops up to include your existing version.

**Comment by folklorelabs** [comment]
Added to the develop branch. It'll be in the next update. Thanks!
https://github.com/folklorelabs/pockest-helper/pull/121
