### ISSUE TITLE
About Ibuki/ Dan/ Notification

### ISSUE THREAD

**Issue by dan1eldn** [folklorelabs/pockest-helper#91]
Here are 3 points,could you fix it or 
1. The Auto-care function does not work properly on character Ibuki.
2. The recently added character Dan is missing.

3.[requirement] The notification function (by API/Mail).

Could you please fix them or give some advices?

**Comment by folklorelabs** [comment]
1. Can you provide any more information? I haven't heard of this issue yet and used it myself to get her successfully. Did you get any errors or anything?
2. The exact conditions are still unknown for Dan
3. What do you mean by this? Are you asking for a new feature?
